💾 Система сохранения персонажей
chelog/dobrograd-13-06-2022 pull request #2
Opened 2023-08-20 11:19 UTC by mlg-intro

Сырая система персонажей, сделано на коленке, старался сделать похожим на ваш кодстайл.
- Нет проверки, сломана ли таблица с сохранениями, поэтому лучше бы добавить уведомление, что сохранения сломаны и удалены.
- Как хранятся и подставляются значения в `model, skin, job` это кринж... лучше бы это тоже чуток поправить.
- В целом каркас готов, надеюсь добавишь на основную ветку <3

@chelog Напиши оценку этому коду, мне очень интересно узнать твое мнение на счет этого коммита :)
![Screenshot_1](https://github.com/chelog/dobrograd-13-06-2022/assets/85566362/5e61b1f0-ea1e-4bcb-9a95-3e2bdb885e5b)

2023-08-22 15:28 UTC, chelog requested changes

2023-08-22 15:28 UTC, chelog commented on garrysmod/addons/_config/lua/config/octogui/f4.lua
> +
Этот список можно и лучше составить/получить из RPExtraTeams, по примеру того, как строится селектор выбора работы

2023-08-22 15:28 UTC, chelog commented on garrysmod/addons/_config/lua/config/octogui/f4.lua
> +			function SetEntryName(text)
Все эти функции глобальные, если они очень нужны, лучше сделать локальными. Но в любом случае не вижу необходимости их добавлять, так как тут всего лишь одно действие выполняется, и лучше отсылаться к переменным с панелями напрямую. Если эти переменные локальные, наверное стоит просто их объявление вынести в скоуп повыше (и назвать поаккуратнее, чтобы было понятно, что к чему относится)

2023-08-22 15:28 UTC, chelog commented on garrysmod/addons/_config/lua/config/octogui/f4.lua
> +				chartable[charVal] = {
Я думаю, эта таблица не нужна в целом. Лучше получать ее, изменять и сохранять за один раз. Можно сделать в начале файла функции вроде `saveCharacterPreset(charID, data)`, и в ней уже делать `octolib.vars.get/set`

2023-08-22 15:28 UTC, chelog commented on garrysmod/addons/_config/lua/config/octogui/f4.lua
> +						end
Думаю, лучше использовать `DImage` для таких вещей, чтобы не изобретать велосипеды с отрисовкой иконки через `Paint`

2023-08-22 15:31 UTC, chelog commented
Отличная работа! На самом деле фича очень нужная, и если ты доработаешь по указанным комментариям, без проблем сможем перенести к нам и при твоем желании рассмотрим кандидатуру на вступление в команду 👀

2023-08-26 15:35 UTC, mlg-intro commented on garrysmod/addons/_config/lua/config/octogui/f4.lua
> +			function SetEntryName(text)
Оказывается в коде уже сохранялась нужная переменная в `f.e_name`. Обращение идет теперь через неё

2023-08-26 15:37 UTC, mlg-intro commented on garrysmod/addons/_config/lua/config/octogui/f4.lua
> +				chartable[charVal] = {
Полностью от нее не смог отказаться, но теперь таблица берётся один раз в нужный момент

2023-08-27 15:20 UTC, chelog requested changes
Все отлично, остались небольшие мелочи, после этого можно будет мерджить 👍

2023-08-27 15:20 UTC, chelog commented on garrysmod/addons/_config/lua/config/octogui/f4.lua
> +				octolib.vars.set('dbg_desc',value['dbg_desc'])
А разве 641 строчка не делает это автоматически? Если нет, то возможно надо использовать `SetValue` вместо `SetText`, чтобы затриггерить коллбек, который на поле ввода уже есть. Я просто не хочу, чтобы одинаковая логика размазывалась на несколько мест, если мы что-то поменяем в том, как хранится описание, мы точно забудем что-то из этого обновить

2023-08-27 15:20 UTC, chelog commented on garrysmod/addons/_config/lua/config/octogui/f4.lua
> +							jbname = job.name
Давай сделаем return сразу тут, тогда и переменную не надо создавать

2023-08-27 15:20 UTC, chelog commented on garrysmod/addons/_config/lua/config/octogui/f4.lua
> +			local function DeleteCharPreset(key)
Названия функций давай переделаем в `camelCase`

2023-08-28 03:59 UTC, mlg-intro commented on garrysmod/addons/_config/lua/config/octogui/f4.lua
> +				octolib.vars.set('dbg_desc',value['dbg_desc'])
Не знал отличия между `SetValue` и `SetText`, теперь понял. С описанием это сработало, но с именем нет. При обновлении F4 имя ставится на то, которое в `cvName`.
`f.e_name:SetValue(value['dbg_name'])` тригерит коллбек, но коллбек не устанавливает значение с textbox в `cvName`. Поэтому добавил в коллбек после 297 строчки `cvName:SetString(self:GetText())` и помогло. Надеюсь так пойдет.

2023-08-28 04:02 UTC, mlg-intro commented on garrysmod/addons/_config/lua/config/octogui/f4.lua
> +			local function DeleteCharPreset(key)
Не совсем понял, все функции переименовать в `camelCase`? То есть получится `DeletecamelCase` , `SavecamelCase` , `LoadcamelCase` и `UpdatecamelCase`?

2023-08-28 06:34 UTC, chelog commented on garrysmod/addons/_config/lua/config/octogui/f4.lua
> +			local function DeleteCharPreset(key)
Есть несколько [регистров](https://medium.com/nerd-for-tech/programming-case-types-explained-143cad3681e3), например `camelCase`, `PascalCase`, `snake_case`, `kebab-case`. У тебя здесь используется `PascalCase`, у нас по код-стайлу такое только для метатаблиц, а для обычных переменных и функций используется `camelCase`

2023-08-28 08:58 UTC, mlg-intro commented on garrysmod/addons/_config/lua/config/octogui/f4.lua
> +			local function DeleteCharPreset(key)
Спасибо за объяснение, теперь буду знать! Поправил названия функций.

2023-08-29 10:18 UTC, GrandMod commented on garrysmod/addons/_config/lua/config/octogui/f4.lua
> +			local function updateCharSet()
В этой функции на всех панелях где ты используешь `Dock` лучше использовать `SetTall/SetWide`. В некоторых панелях у тебя используются все три, вместе с `SetSize`. Нужно использовать что-то одно: `SetSize` или `Dock` вместе с `SetTall/SetWide`(кроме моментов когда ты используешь `Dock(FILL)`)

2023-08-30 13:38 UTC, mlg-intro commented on garrysmod/addons/_config/lua/config/octogui/f4.lua
> +			local function updateCharSet()
Спасибо за объяснение, поправил.

2023-09-19 20:43 UTC, merged

2023-09-19 20:44 UTC, chelog commented
Извини за задержку - был в дороге длительное время. Все отлично, спасибо за твой труд! Заведем задачку на интеграцию этих изменений в основной проект 💪