Починить сборку
chelog/dobrograd-13-06-2022 pull request #5
Opened 2023-12-29 03:46 UTC by t1m1yep

# Список фиксов:
### Изменил MARIADB_ALLOW_EMPTY_ROOT_PASSWORD с "true" на "1" (docker-compose.yml)
### Убрал config.ts из .gitignore
### Поставил везде название БД gmod_dobrograd
### Поправил путь конфига в TS
### Переместил octolib/addon в garrysmod/addons/core-octolib
### Поправил config.ts, теперь не надо заморачиваться с настройкой гейммода
### Починил RCON - добавил в octolib/core/gameServer.ts строки:
`-ip 0.0.0.0`
`+net_public_adr 89.35.52.89`
### Поправил server.cfg

### Предисловие
**Хотел запустить сборку (потому что я в [пермабане..](https://forum.octothorp.team/topic/6542/%D0%B7%D0%B0%D1%8F%D0%B2%D0%BA%D0%B0-%D0%BD%D0%B0-%D1%80%D0%B0%D0%B7%D0%B1%D0%B0%D0%BD-%D1%81%D0%BF%D1%83%D1%81%D1%82%D1%8F-%D0%B4%D0%B2%D0%B0-%D0%B3%D0%BE%D0%B4%D0%B0?_=1703814273996)) в итоге выдало ошибку и я решил починить ее, теперь отправляю пулл реквест**
**- t1m1yep, который ждет рассмотрения [заявки](https://forum.octothorp.team/topic/6542/%D0%B7%D0%B0%D1%8F%D0%B2%D0%BA%D0%B0-%D0%BD%D0%B0-%D1%80%D0%B0%D0%B7%D0%B1%D0%B0%D0%BD-%D1%81%D0%BF%D1%83%D1%81%D1%82%D1%8F-%D0%B4%D0%B2%D0%B0-%D0%B3%D0%BE%D0%B4%D0%B0?_=1703814273996) 30 дней :)**

2023-12-29 11:40 UTC, t1m1yep commented
@chelog жду ревью

2023-12-29 11:57 UTC, chelog requested changes

2023-12-29 11:57 UTC, chelog commented on octolib/core/gameServer.ts
> +		'+net_public_adr 89.35.52.89',
Чей это адрес? Если хочется добавлять этот параметр, надо вынести его в конфиг

2023-12-29 11:57 UTC, chelog commented on .gitignore
> -config.ts
Этот файл предназначен для локальной конфигурации, так как там могут быть чувствительные данные - конфиги и прочее. Пример конфига должен лежать отдельно от реального локального конфига

2023-12-29 11:57 UTC, chelog commented on config.ci.ts
> +import Config from './octolib/core/config'
Октолиба сама симлинкается в аддоны, это сделано в первую очередь из-за того, что она является гит-подмодулем. Хоть в данном репозитории она и лежит простой папкой, я бы не хотел ломать совместимость и перелопачивать все в репозитории. Лучше сделать дополнительные хелперы, которые будут выполнять недостающие упрощающие жизнь действия, если таковые нужны

2023-12-29 11:57 UTC, chelog commented on config.ci.ts
> -	shop: 'gmod_dbg_dev',
Зачем изменено название базы данных? Тут специально помечено, что это тестовая, а не продакшн-база, не вижу  смысла вносить изменения, которые не приносят никакой практической пользы

2023-12-29 11:57 UTC, chelog commented on config.ci.ts
> -const config = Object.assign({}, base)
Здесь специально все было сделано таким образом, чтобы оверрайдить забовый конфиг. Если ты хочешь прописать какие-то параметры по дефолту для Доброграда, просто пропиши их в config.example, а не заменяй базовый конфиг

2023-12-29 11:57 UTC, chelog commented on octolib/npm-debug.log
> +0 info it worked if it ends with ok
Артефактов не должно быть в репозитории

2023-12-29 11:57 UTC, chelog commented on server.cfg
> +sv_defaultgamemode = "darkrp"
Это не похоже на параметры, которые подаются в stdin, к тому же они проставляются автоматически из скрипта запуска

2023-12-29 11:59 UTC, chelog commented on docker-compose.yml
> -      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
Достаточно обернуть "true" в кавычки

2023-12-29 20:09 UTC, mlg-intro commented
В целом фиксом это и не могу назвать, ничего не фиксится, даже наоборот ломается... Проще будет закрыть мердж, Дима по всем изменениям, (я их тоже хотел написать, но Дима оказался быстрее :) )

2023-12-30 02:12 UTC, t1m1yep commented
у нас отмена, я еблан немного

2023-12-30 02:12 UTC, closed without merging